### ISSUE TITLE
[Insanity check] Refactor ImportActivity

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#289]
Existing activity does actually work, but its implementation is beyond all redemption

**TODO**
- [x] List all use cases
- [x] List all interactions (~~dirpicker~~, SAF system dialog, import service)
- [x] List all inputs and outputs
- [x] Rewrite the whole process from scratch; try and make something STATELESS

**HIGHLIGHTS**
- ~~Remove the dirpicker; file selection should be done exclusively with the SAF dialog~~ DONE v1.9.0
- [x] Replace deprecated `ProgressDialog` with something clean and modal (i.e. that cannot be accidentally dismissed, leaving the user blind)
- [x] Refresh / import progress should also appear on a notification, for users to check it when the app runs in background

**Comment by RobbWatershed** [comment]
Wightwulf@2019/03/27
https://commonsware.com/blog/2019/03/25/death-external-storage-what-now.html

Even tighter restrictions on external storage. Pretty soon the only way for apps to store downloaded files are the ff:

* internal app storage which may or may not be on the sd card. Will be deleted when the app is uninstalled.
* public external folders such as the downloads or pictures folder which may or may not be on the sd card.
* an unknown location that can only be referenced through a content: uri. The user is asked to select the location using the SAF dialog similar to a select folder dialog .
---
I still believe that the safest design for Hentoid is a combination of the 1st and 3rd option where downloads are managed by Hentoid and inaccessible to users through option 1, with an export function where the user is asked where to export to using option 3.

The rationale behind this is the following requirements:

* Hentoid needs to be able to freely access files it downloads and manages. This is only achievable through option 1 & 2
* The files must be hidden from the Android's media indexer so images don't appear in the regular gallery/photos app. This is only achievable through option 1 and option 3 if the user is smart about it.
* The user must be able to freely access the files downloaded by hentoid. Only achievable through option 2 & 3

So as you can see in the above requirements just 1 approach to the problem will not suffice

-------

also just a reminder that in the context of android external storage just means it's not inside the app's storage folder that's deleted when it is uninstalled. This is a different entity from removable storage which may be an SD card ord USB-OTG drive. An external storage may or may not be on removable storage.

**Comment by RobbWatershed** [comment]
2019/05/09 - Decision to drop dirpicker in favour of SAF + raise minSdkVersion to 19 (Android 4.4, where SAF has been introduced)

**Comment by avluis** [comment]
In relation to #191 
I remember coming to the same conclusion above -- saving files to a world readable directory is bad for management and security.
I think I even threw in a few utility classes as well as a zip utility;
Try selecting a book by pressing and holding the entry in `Downloads` -- the third option (Archive) packs the files and requests a share intent iirc

**Comment by ArturRA** [comment]
Improve the transition to the import progress actually starting. Currently when using the "Select Downloads Folder" option in preference a black screen appears that stay black proportional to the size of the collection(more testing needed).
Also when the import does start and the progress bar appears if you click anywhere it is dismissed leaving the user with no way to know the actual progress and if it is happening.
The notification saying the process is running doesn't say the percentage of completion(books imported/books total).

**Comment by RobbWatershed** [comment]
See #381 and https://www.reddit.com/r/Hentoid/comments/eccfso/anyone_else_have_their_app_hang_or_freeze_up_when/ concerning the import progress dialog that can be hidden by mistake by the user

**Comment by RobbWatershed** [comment]
D.O.N.E.
